version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@9.0.0
workflows:
  build_and_push_image:
    jobs:
      - build_and_push_image:
          filters:
            branches:
              only: main
          context: dev
jobs:
  build_and_push_image:
    docker:
      - image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - aws-ecr/build_and_push_image:
          public_registry: true
          repo: apj-demo-2
          create_repo: true
          region: ap-southeast-1
          auth:
            - aws-cli/setup:
                role_arn: ${AWS_ROLE}

