version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.1
  aws-ecr: circleci/aws-ecr@8.1.2
workflows:
  build_and_push_image:
    jobs:
      - aws-cli/setup:
         role-arn: ${AWS_ROLE}
         aws-region: "ap-southeast-1"
         # optional parameters
         role-session-name: “ci-session”
         session-duration: 1800
         context: dev
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only: main
          context: dev
          public-registry: true
          repo: apj-demo-2
